---
# Volume claim using jenkins-home-pv volume
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-home-pvc
  namespace: jenkins
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "10Gi"
  volumeName: jenkins-home-pv
  storageClassName: ""

