
resources:
  requests:
    cpu: "100m"
    memory: "256Mi"
  limits:
    cpu: "500m"
    memory: "4Gi"

persistence:
  enabled: true
  ## If defined, PVC must be created manually before volume will be bound
  existingClaim: jenkins-home-pvc
