k8s_cp:
  hosts:
    kmaster:

k8s_workers:
  hosts:
    kworker01:
    kworker02:

k8s:
  children:
    k8s_cp:
    k8s_workers:

linux_vms:
  hosts:
    neptune:

all:
  vars:
    domain_name: ramvarra.com
    timezone: "America/Phoenix"
    k8s_version: "1.28"
    k8s_pod_cidr: "10.10.0.0/16"
    k8s_user: rrvarra
