
- name: Test
  hosts: k8s
  become: true

  tasks:
  - name: Install k8s pre-requisite and other useful package
    ansible.builtin.apt:
      name:
      - ca-certificates 
      - apt-transport-https
      - curl 
      - gnupg
      update_cache: true

  - name: Add Docker’s official GPG key
    ansible.builtin.apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present

  - name: Add Docker DEB Repository
    ansible.builtin.apt_repository:
      repo: "deb https://download.docker.com/linux/ubuntu {{ansible_lsb.codename}} stable"
      state: present
      mode: 0600

  - name: Install docker and containerd
    ansible.builtin.apt:
      name: 
        - docker-ce 
        - docker-ce-cli 
        - containerd.io 
      update_cache: true

  - name: Ensure docker service is enabled and running
    ansible.builtin.service:
      name: docker
      enabled: true
      state: started
  
  - name: Add self to docker group
    ansible.builtin.user:
      name: "{{ lookup('env', 'USER') }}"
      groups: docker
      append: yes
  
  
  - name: Check if containerd is configured
    ansible.builtin.command: grep '^disabled_plugins = \["cri"\]' /etc/containerd/config.toml
    register: containerd_config_check
    failed_when: false
    changed_when: false

  - name: Initialize containerd configuration
    ansible.builtin.shell: "containerd config default > /etc/containerd/config.toml"
    when: containerd_config_check.rc == 0

  - name: Setup containerd to use Systemd driver
    ansible.builtin.lineinfile:
      path: /etc/containerd/config.toml
      regexp: '^\s+SystemdCgroup = false'
      line: "            SystemdCgroup = true"
    notify: Restart containerd


  - name: Add Google official GPG key
    ansible.builtin.apt_key:
      url: "https://pkgs.k8s.io/core:/stable:/v{{k8s_version}}/deb/Release.key"
      state: present

  - name: Add Kubernetes Repository
    apt_repository:
      repo: deb https://pkgs.k8s.io/core:/stable:/v1.28/deb/ /
      state: present
      filename: kubernetes

  - name: Install kubernetes packages
    ansible.builtin.apt:
      name:
        - kubelet 
        - kubeadm 
        - kubectl
      state: present
      update_cache: true

  - name: Hold kubernetes packages
    ansible.builtin.dpkg_selections:
      name: "{{ item }}"
      selection: hold
    with_items: 
      - kubelet
      - kubeadm
      - kubectl
      - docker-ce 
      - docker-ce-cli 
      - containerd.io 

  - name: Ensure kubelet is enabled
    ansible.builtin.service:
      name: kubelet
      enabled: true
      state: started
    notify: Reboot all 

  handlers:
  - name: Restart containerd
    ansible.builtin.service:
      name: containerd
      state: restarted

  - name: Reboot all
    reboot:
      test_command: uptime

