
---
- name: Configure SSH
  hosts: k8s
  become: true

  tasks:
  - name: setup authorized key
    ansible.posix.authorized_key:
      user: {{k8s_user}}
      state: present
      key: "{{ lookup('file', 'templates/ssh-authorized-keys') }}"

  - name: setup rrvarra to be passwordless sudo
    ansible.builtin.lineinfile:
      path: /etc/sudoers
      state: present
      regexp: "^{{k8s_user}} "
      line: "{{k8s_user}} ALL=(ALL:ALL) NOPASSWD: ALL"
      validate: 'visudo -cf %s'


