---
- name: Configure SSH
  hosts: k8s
  become: true

  roles:
  - role: systemd-timesyncd
    timesync_timezone: "{{ timezone }}"
    timesync_ntp_hosts:
      - time.google.com

  tasks:

  - name: Validate all machine_ids abnd product_ids are unqiue
    ansible.builtin.script:
      cmd: scripts/check-unique.py {% for host in ansible_play_hosts %}{{ hostvars[host].ansible_facts[item] }} {% endfor %}
      executable: /usr/bin/python3
    run_once: true
    delegate_to: localhost
    changed_when: false
    loop:
      - product_uuid
      - machine_id

  - name: Validate all MACs are unique
    ansible.builtin.script:
      cmd: scripts/check-unique.py {% for host in ansible_play_hosts %}{{ hostvars[host]['ansible_facts']['ens160']['macaddress'] }} {% endfor %}
      executable: /usr/bin/python3
    run_once: true
    delegate_to: localhost
    changed_when: false

  - import_tasks: set-host.yaml

  - name: Disable UFW
    ansible.builtin.service:
      name: ufw
      enabled: false
      state: stopped

  - name: Disable swap in fstat (permanent)
    ansible.builtin.replace:
      path: /etc/fstab
      regexp: '^([^#].*?\sswap\s+sw\s+.*)$'
      replace: '# \1'

  - name: Turn off swap
    ansible.builtin.command: swapoff -a
    changed_when: false

  - name: Install nfs-common on worker nodes
    ansible.builtin.apt:
      name:
        - nfs-common
      state: present
      update_cache: true
    when: inventory_hostname in groups['k8s_workers']

  - name: sysctl vm.swappiness=0
    ansible.builtin.sysctl:
      name: vm.swappiness
      value: '0'
      sysctl_file: /etc/sysctl.d/10-swappiness.conf
      state: present

  - name: Copy
    ansible.builtin.copy:
      dest: /etc/modules-load.d/k8s.conf
      content: |
        overlay
        br_netfilter

  - name: Load kernel modules
    ansible.builtin.shell: modprobe {{ item }}
    loop:
      - overlay
      - br_netfilter
    changed_when: false

  - name: Set sysctl settings
    ansible.builtin.sysctl:
      name: "{{ item.name }}"
      value: "{{ item.value }}"
      sysctl_file: /etc/sysctl.d/k8s.conf
      state: present
    with_items:
      - name: net.bridge.bridge-nf-call-iptables
        value: 1
      - name: net.bridge.bridge-nf-call-ip6tables
        value: 1
      - name: net.ipv4.ip_forward
        value: 1


