---
- name: Configure SSH
  hosts: k8s
  become: true

  roles:
  - role: systemd-timesyncd
    timesync_timezone: "{{ timezone }}"
    timesync_ntp_hosts:
      - time.google.com

  tasks:
  - name: Verify machine_ids are unique
    ansible.builtin.script: "/usr/bin/python3 scripts/check-unique.py {% for host in ansible_play_hosts %}{{ hostvars[host]['ansible_facts']['machine_id'] }} {% endfor %}"
    run_once: true
    delegate_to: localhost
    changed_when: false

  - name: Update apt
    ansible.builtin.apt:
      update_cache: yes
      cache_valid_time: 7200


  - name: Configure hosts for fqdn
    ansible.builtin.lineinfile:
      path: /etc/hosts
      state: present
      regexp: '^127.0.1.1 '
      line: '127.0.1.1 {{ inventory_hostname }}.{{ domain_name }}  {{ inventory_hostname }}'

  - name: Verify hostname matches inventory host
    ansible.builtin.hostname:
      name: "{{ inventory_hostname }}"
  
  - name: Verify FQDN
    ansible.builtin.debug: 
      msg: "FQDN OK - {{ansible_fqdn}}"
    failed_when: ansible_fqdn != (inventory_hostname + '.' + domain_name)

  - name: Verify IP
    ansible.builtin.debug:
      msg: "DNSIP: {{ lookup('community.dns.lookup', inventory_hostname+'.ramvarra.com.') }} HOSTIP: {{ ansible_default_ipv4.address }}"
    #failed_when: lookup('community.dns.lookup', inventory_hostname+'.'+domain_name+'.') != ansible_default_ipv4.address
    failed_when: lookup('community.dns.lookup', inventory_hostname+'.'+domain_name+'.') != ansible_default_ipv4.address

  - name: Disable UFW
    ansible.builtin.service:
      name: ufw
      enabled: false
      state: stopped

  - name: Disable swap in fstat (permanent)
    ansible.builtin.replace:
      path: /etc/fstab
      regexp: '^([^#].*?\sswap\s+sw\s+.*)$'
      replace: '# \1'

  - name: Turn off swap 
    ansible.builtin.command: swapoff -a
    changed_when: false

  - name: Install nfs-common on worker nodes
    ansible.builtin.apt:
      name:
        - nfs-common
      state: present
    when: inventory_hostname in groups['k8s_workers']
